# -*- coding: utf-8 -*-
"""python-course-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xI3DIg2F-dXQPkdjCuDX1fxVfyDLZ_wi
"""

#Import
import pandas as pd
import os
import requests

"""**Extract:**"""

# @title
# housing_prices-API
#120010=ID, סוג המידע
#format=json
#startPeriod=01-2011
url_housing_prices = "https://api.cbs.gov.il/index/data/price?id=120010&format=json&download=false&startPeriod=01-2011&PageSize=1000"

data_housing_prices = requests.get(url_housing_prices).json()
df_housing_prices = pd.DataFrame(data_housing_prices["month"][0]["date"])

#df_housing_prices
os.makedirs("raw_data", exist_ok=True)
df_housing_prices.to_csv("raw_data/housing_prices_source.csv", index=False, encoding='utf-8')
df_housing_prices.to_csv("housing_prices.csv", index=False, encoding='utf-8')

# @title
# israel_macro_events- CSV
url_israel_macro_events = "https://raw.githubusercontent.com/Idohazan/python-course-project/refs/heads/main/israel_macro_events.csv"

df_israel_macro_events = pd.read_csv(url_israel_macro_events)


os.makedirs("raw_data", exist_ok=True)
df_israel_macro_events.to_csv("raw_data/israel_macro_events.csv", index=False, encoding='utf-8')
df_israel_macro_events.to_csv("israel_macro_events.csv", index=False, encoding='utf-8')

# @title
#interest_rates - CSV
url_interest_rates = "https://raw.githubusercontent.com/Idohazan/python-course-project/refs/heads/main/Israel_interest_rates.csv"

df_interest_rates = pd.read_csv(url_interest_rates)

#df_interest_rates
os.makedirs("raw_data", exist_ok=True)
df_interest_rates.to_csv("raw_data/interest_rates_source.csv", index=False, encoding='utf-8')
df_interest_rates.to_csv("interest_rates.csv", index=False, encoding='utf-8-sig')

"""**Transform:**"""

# @title
df_housing_prices
df_housing_prices['date']=pd.to_datetime(dict(year=df_housing_prices['year'],month=df_housing_prices['month'],day=1))

df_housing_prices['index_value']=df_housing_prices['currBase'].str['value']
df_housing_prices['index_value'] = df_housing_prices['index_value'] / 100
df_housing_prices=df_housing_prices[['date','percent','percentYear','index_value']]

df_housing_prices.head()

# @title

#df_israel_macro_events.info()
df_israel_macro_events['date'] = pd.to_datetime(df_israel_macro_events.pop('Date'))

# === הוספה: קליטת תאריך הסיום (EndDate) או הגדרת ברירת מחדל ליום אחד ===
if 'EndDate' in df_israel_macro_events.columns:
    df_israel_macro_events['end_date'] = pd.to_datetime(df_israel_macro_events.pop('EndDate'))
elif 'end_date' in df_israel_macro_events.columns:
    df_israel_macro_events['end_date'] = pd.to_datetime(df_israel_macro_events.pop('end_date'))
else:
    df_israel_macro_events['end_date'] = df_israel_macro_events['date']

df_interest_rates.columns = df_interest_rates.columns.str.lower()
df_interest_rates=df_interest_rates[['time_period','obs_value']].copy()
df_interest_rates.columns  = ['date','interest_rate']


df_interest_rates['date']=pd.to_datetime(df_interest_rates['date'])


df_interest_rates=df_interest_rates[df_interest_rates['date'].dt.day ==1]

"""Load"""

df_final=(
      df_housing_prices
      .merge(df_interest_rates,on='date',how='inner')
      .merge(df_israel_macro_events,on='date',how='left')


)

df_final.to_csv('israel_housing_dashboard_data.csv', index=False, encoding='utf-8-sig')